import { State } from "./types";

export const initialState: State = {
  value: 0,
  open: false,
  editPatient: false,
  patient: {
    id: null,
    fullName: "",
    sex: 0,
    birthdate: "2000-01-01",
    dateOfVisit: new Date().toISOString().split("T")[0],
    address: "",
    email: "",
    phone: "",
    status: 0,
    created_at: new Date().toISOString().split("T")[0],
    updated_at: null,
    lms_company_id: null,
    lms_referral_id: null,
    lms_hmo_id: null,
  },
  updateProfile: {
    id: null,
    fullName: "",
    sex: 0,
    birthdate: "2000-01-01",
    dateOfVisit: new Date().toISOString().split("T")[0],
    address: "",
    email: "",
    phone: "",
    status: 0,
    created_at: null,
    updated_at: new Date().toISOString().split("T")[0],
    lms_company_id: null,
    lms_referral_id: null,
    lms_hmo_id: null,
  },
  age: 0,
  patients: [],
  testCategory: [],
  checkedCategory: [],
  onRemoveCheckedCat: [],
  addedTests: [],
};
